--[[
    init.lua
    Created: 08/16/2024 20:09:00
    Description: Autogenerated script file for the map personality_test.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local personality_test = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---personality_test.Init(zone)
--Engine callback function
function personality_test.Init(zone)


end

---personality_test.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function personality_test.EnterSegment(zone, rescuing, segmentID, mapID)


end

---personality_test.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function personality_test.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---personality_test.Rescued(zone, name, mail)
--Engine callback function
function personality_test.Rescued(zone, name, mail)


end

return personality_test

